export const EASTERE_EGG_STATUS = ['idle', 'called', 'read'] as const
export const EASTERE_EGG_NUMBER_KEYS = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'] as const
export const EASTERE_EGG_SYMBOL_KEYS = ['`', '-', '=', '[', ']', '\\', ';', "'", ',', '.', '/'] as const
export const EASTERE_EGG_FUNCTION_KEYS = [
  'f1',
  'f2',
  'f3',
  'f4',
  'f5',
  'f6',
  'f7',
  'f8',
  'f9',
  'f10',
  'f11',
  'f12',
] as const
export const EASTERE_EGG_LETTER_KEYS = [
  'a',
  'b',
  'c',
  'd',
  'e',
  'f',
  'g',
  'h',
  'i',
  'j',
  'k',
  'l',
  'm',
  'n',
  'o',
  'p',
  'q',
  'r',
  's',
  't',
  'u',
  'v',
  'w',
  'x',
  'y',
  'z',
] as const
export const EASTERE_EGG_NUMPAD_KEYS = [
  'num_0',
  'num_1',
  'num_2',
  'num_3',
  'num_4',
  'num_5',
  'num_6',
  'num_7',
  'num_8',
  'num_9',
  'num_multiply',
  'num_add',
  'num_enter',
  'num_subtract',
  'num_decimal',
  'num_divide',
] as const
export const EASTERE_EGG_SPECIAL_KEYS = [
  'backspace',
  'tab',
  'enter',
  'return',
  'shift',
  'ctrl',
  'control',
  'alt',
  'option',
  'capslock',
  'esc',
  'escape',
  'space',
  'pageup',
  'pagedown',
  'end',
  'home',
  'left',
  'up',
  'right',
  'down',
  'ins',
  'insert',
  'del',
  'delete',
  'meta',
  'command',
  'cmd',
  'clear',
] as const

export const EASTERE_EGG_ALL_KEYS = [
  ...EASTERE_EGG_NUMBER_KEYS,
  ...EASTERE_EGG_FUNCTION_KEYS,
  ...EASTERE_EGG_SYMBOL_KEYS,
  ...EASTERE_EGG_LETTER_KEYS,
  ...EASTERE_EGG_NUMPAD_KEYS,
  ...EASTERE_EGG_SPECIAL_KEYS,
] as const
