export const Z80_MEMORY = {
  size: 0x10000,
} as const

export const Z80_FLAG = {
  sign: 0x80,
  zero: 0x40,
  halfCarry: 0x10,
  parityOverflow: 0x04,
  subtract: 0x02,
  carry: 0x01,
} as const

export const Z80_CPU = {
  operands8: ['b', 'c', 'd', 'e', 'h', 'l', null, 'a'],
  rotateOperations: ['rlc', 'rrc', 'rl', 'rr', 'sla', 'sra', null, 'srl'],
} as const

export const Z80_CYCLES = {
  aluN: 7,
  aluR: 4,
  aluHL: 7,
  addHLRegisterPair: 11,
  cbBitHL: 12,
  cbModifyHL: 15,
  cbRegister: 8,
  callNN: 17,
  callConditionalNotTaken: 10,
  callConditionalTaken: 17,
  diEi: 4,
  djnzNotTaken: 8,
  djnzTaken: 13,
  exchangeRegister: 4,
  exchangeStackHL: 19,
  flagControl: 4,
  halt: 4,
  incDecR: 4,
  incDecRegister16: 6,
  jpNN: 10,
  jpConditional: 10,
  jr: 12,
  jrConditionalNotTaken: 7,
  jrConditionalTaken: 12,
  ldAFromAbsoluteMemory: 13,
  ldAFromMemoryAtRegisterPair: 7,
  ldAbsoluteMemoryFromA: 13,
  ldAbsoluteMemoryFromHL: 16,
  ldHLFromAbsoluteMemory: 16,
  ldMemoryAtRegisterPairFromA: 7,
  ldMemoryHLFromRegister: 7,
  ldMemoryHLImmediate: 10,
  ldRN: 7,
  ldRR: 4,
  ldRRNN: 10,
  ldRegisterFromMemoryHL: 7,
  ldSPFromHL: 6,
  nop: 4,
  popRegisterPair: 10,
  pushRegisterPair: 11,
  ret: 10,
  retConditionalNotTaken: 5,
  retConditionalTaken: 11,
  rotateAccumulator: 4,
  rst: 11,
} as const
