// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };


type PickContentRelationshipFieldData<
	TRelationship extends prismic.CustomTypeModelFetchCustomTypeLevel1 | prismic.CustomTypeModelFetchCustomTypeLevel2 | prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2,
	TData extends Record<string, prismic.AnyRegularField | prismic.GroupField | prismic.NestedGroupField | prismic.SliceZone>,
	TLang extends string
> = |
	// Content relationship fields
	{
		[TSubRelationship in Extract<
			TRelationship["fields"][number], prismic.CustomTypeModelFetchContentRelationshipLevel1
		> as TSubRelationship["id"]]:
			ContentRelationshipFieldWithData<TSubRelationship["customtypes"], TLang>;
	} &
	// Group
	{
		[TGroup in Extract<
			TRelationship["fields"][number], prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2
		> as TGroup["id"]]:
			TData[TGroup["id"]] extends prismic.GroupField<infer TGroupData>
				? prismic.GroupField<PickContentRelationshipFieldData<TGroup, TGroupData, TLang>>
				: never
	} &
	// Other fields
	{
		[TFieldKey in Extract<TRelationship["fields"][number], string>]:
			TFieldKey extends keyof TData ? TData[TFieldKey] : never;
	};

type ContentRelationshipFieldWithData<
	TCustomType extends readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[] | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
	TLang extends string = string
> = {
	[ID in Exclude<TCustomType[number], string>["id"]]:
		prismic.ContentRelationshipField<
			ID,
			TLang,
			PickContentRelationshipFieldData<
				Extract<TCustomType[number], { id: ID }>,
				Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
				TLang
			>
		>
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Primary content in *About → Slice zone → Page Config → Primary*
 */
export interface AboutDocumentDataBodyPageConfigSlicePrimary {
	/**
	 * Background field in *About → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about.body[].page_config.primary.background_color
	 * - **Documentation**: https://prismic.io/docs/fields/color
	 */
	background_color: prismic.ColorField;
	
	/**
	 * SEO Title field in *About → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about.body[].page_config.primary.seo_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	seo_title: prismic.KeyTextField;
	
	/**
	 * SEO Description field in *About → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about.body[].page_config.primary.seo_description
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	seo_description: prismic.KeyTextField;
	
	/**
	 * SEO URL field in *About → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about.body[].page_config.primary.seo_url
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	seo_url: prismic.KeyTextField;
	
	/**
	 * Open Graph Type field in *About → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: website
	 * - **API ID Path**: about.body[].page_config.primary.og_type
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	og_type: prismic.SelectField<"website" | "article" | "product" | "profile" | "video.movie", "filled">;
	
	/**
	 * Open Graph Title field in *About → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about.body[].page_config.primary.og_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	og_title: prismic.KeyTextField;
	
	/**
	 * Open Graph Description field in *About → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about.body[].page_config.primary.og_description
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	og_description: prismic.KeyTextField;
	
	/**
	 * Open Graph Image field in *About → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about.body[].page_config.primary.og_image
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	og_image: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * Twitter Card field in *About → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: summary_large_image
	 * - **API ID Path**: about.body[].page_config.primary.twitter_card
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	twitter_card: prismic.SelectField<"summary_large_image" | "summary" | "player" | "app", "filled">;
	
	/**
	 * Twitter Title field in *About → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about.body[].page_config.primary.twitter_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	twitter_title: prismic.KeyTextField;
	
	/**
	 * Twitter Description field in *About → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about.body[].page_config.primary.twitter_description
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	twitter_description: prismic.KeyTextField;
	
	/**
	 * Twitter Image field in *About → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about.body[].page_config.primary.twitter_image
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	twitter_image: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Slice for *About → Slice zone*
 */
export type AboutDocumentDataBodyPageConfigSlice = prismic.Slice<"page_config", Simplify<AboutDocumentDataBodyPageConfigSlicePrimary>, never>

type AboutDocumentDataBodySlice = AboutDocumentDataBodyPageConfigSlice

/**
 * Content for About documents
 */
interface AboutDocumentData {
	/**
	 * Título field in *About*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Alex Madeira
	 * - **API ID Path**: about.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Sub título field in *About*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about.sub_title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	sub_title: prismic.KeyTextField;
	
	/**
	 * Descrição field in *About*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
	
	/**
	 * Video field in *About*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about.movie
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	movie: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;/**
	 * Slice zone field in *About*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about.body[]
	 * - **Tab**: Config
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	body: prismic.SliceZone<AboutDocumentDataBodySlice>;
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<AboutDocumentData>, "about", Lang>;

/**
 * Content for Award documents
 */
interface AwardDocumentData {
	/**
	 * Nome field in *Award*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: award.name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	name: prismic.KeyTextField;
	
	/**
	 * Data field in *Award*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: *None*
	 * - **API ID Path**: award.date
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/date
	 */
	date: prismic.DateField;
	
	/**
	 * Descrição field in *Award*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: award.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	description: prismic.KeyTextField;
}

/**
 * Award document from Prismic
 *
 * - **API ID**: `award`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AwardDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<AwardDocumentData>, "award", Lang>;

/**
 * Content for Brand documents
 */
interface BrandDocumentData {
	/**
	 * Nome field in *Brand*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: brand.name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	name: prismic.KeyTextField;
	
	/**
	 * Logo field in *Brand*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: brand.logo
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	logo: prismic.ImageField<never>;
}

/**
 * Brand document from Prismic
 *
 * - **API ID**: `brand`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BrandDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<BrandDocumentData>, "brand", Lang>;

/**
 * Content for Company documents
 */
interface CompanyDocumentData {
	/**
	 * Nome field in *Company*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: company.name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	name: prismic.KeyTextField;
	
	/**
	 * Cargo field in *Company*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: company.role
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	role: prismic.KeyTextField;
	
	/**
	 * De field in *Company*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: *None*
	 * - **API ID Path**: company.start_date
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/date
	 */
	start_date: prismic.DateField;
	
	/**
	 * até field in *Company*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: *None*
	 * - **API ID Path**: company.end_date
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/date
	 */
	end_date: prismic.DateField;
	
	/**
	 * Descrição field in *Company*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: company.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
}

/**
 * Company document from Prismic
 *
 * - **API ID**: `company`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CompanyDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<CompanyDocumentData>, "company", Lang>;

/**
 * Primary content in *Home → Slice zone → Page Config → Primary*
 */
export interface HomeDocumentDataBodyPageConfigSlicePrimary {
	/**
	 * Background field in *Home → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home.body[].page_config.primary.background_color
	 * - **Documentation**: https://prismic.io/docs/fields/color
	 */
	background_color: prismic.ColorField;
	
	/**
	 * SEO Title field in *Home → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home.body[].page_config.primary.seo_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	seo_title: prismic.KeyTextField;
	
	/**
	 * SEO Description field in *Home → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home.body[].page_config.primary.seo_description
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	seo_description: prismic.KeyTextField;
	
	/**
	 * SEO URL field in *Home → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home.body[].page_config.primary.seo_url
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	seo_url: prismic.KeyTextField;
	
	/**
	 * Open Graph Type field in *Home → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: website
	 * - **API ID Path**: home.body[].page_config.primary.og_type
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	og_type: prismic.SelectField<"website" | "article" | "product" | "profile" | "video.movie", "filled">;
	
	/**
	 * Open Graph Title field in *Home → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home.body[].page_config.primary.og_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	og_title: prismic.KeyTextField;
	
	/**
	 * Open Graph Description field in *Home → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home.body[].page_config.primary.og_description
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	og_description: prismic.KeyTextField;
	
	/**
	 * Open Graph Image field in *Home → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home.body[].page_config.primary.og_image
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	og_image: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * Twitter Card field in *Home → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: summary_large_image
	 * - **API ID Path**: home.body[].page_config.primary.twitter_card
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	twitter_card: prismic.SelectField<"summary_large_image" | "summary" | "player" | "app", "filled">;
	
	/**
	 * Twitter Title field in *Home → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home.body[].page_config.primary.twitter_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	twitter_title: prismic.KeyTextField;
	
	/**
	 * Twitter Description field in *Home → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home.body[].page_config.primary.twitter_description
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	twitter_description: prismic.KeyTextField;
	
	/**
	 * Twitter Image field in *Home → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home.body[].page_config.primary.twitter_image
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	twitter_image: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Slice for *Home → Slice zone*
 */
export type HomeDocumentDataBodyPageConfigSlice = prismic.Slice<"page_config", Simplify<HomeDocumentDataBodyPageConfigSlicePrimary>, never>

type HomeDocumentDataBodySlice = HomeDocumentDataBodyPageConfigSlice

/**
 * Content for Home documents
 */
interface HomeDocumentData {
	/**
	 * Título field in *Home*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Alex Madeira
	 * - **API ID Path**: home.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Descrição field in *Home*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;/**
	 * Slice zone field in *Home*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home.body[]
	 * - **Tab**: Config
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	body: prismic.SliceZone<HomeDocumentDataBodySlice>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Item in *Project → tecnologias*
 */
export interface ProjectDocumentDataTechnologiesItem {
	/**
	 * Tecnologia field in *Project → tecnologias*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.technologies[].technology
	 * - **Documentation**: https://prismic.io/docs/fields/content-relationship
	 */
	technology: prismic.ContentRelationshipField<"technology">;
}

/**
 * Primary content in *Project → Slice zone → Bloco Full Image → Primary*
 */
export interface ProjectDocumentDataBlocksBlocoFullImageSlicePrimary {
	/**
	 * Cor field in *Project → Slice zone → Bloco Full Image → Primary*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.blocks[].bloco_full_image.primary.color
	 * - **Documentation**: https://prismic.io/docs/fields/color
	 */
	color: prismic.ColorField;
	
	/**
	 * Imagem field in *Project → Slice zone → Bloco Full Image → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.blocks[].bloco_full_image.primary.image
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	image: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * Tamanho field in *Project → Slice zone → Bloco Full Image → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: full
	 * - **API ID Path**: project.blocks[].bloco_full_image.primary.size
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	size: prismic.SelectField<"full" | "center", "filled">;
}

/**
 * Slice for *Project → Slice zone*
 */
export type ProjectDocumentDataBlocksBlocoFullImageSlice = prismic.Slice<"bloco_full_image", Simplify<ProjectDocumentDataBlocksBlocoFullImageSlicePrimary>, never>

/**
 * Primary content in *Project → Slice zone → Bloco Imagem Grid → Primary*
 */
export interface ProjectDocumentDataBlocksBlocoImagemGridSlicePrimary {
	/**
	 * Numero de colunas field in *Project → Slice zone → Bloco Imagem Grid → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.blocks[].bloco_imagem_grid.primary.columns
	 * - **Documentation**: https://prismic.io/docs/fields/number
	 */
	columns: prismic.NumberField;
	
	/**
	 * Espaçamento field in *Project → Slice zone → Bloco Imagem Grid → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: true
	 * - **API ID Path**: project.blocks[].bloco_imagem_grid.primary.gap
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	gap: prismic.BooleanField;
}

/**
 * Item content in *Project → Slice zone → Bloco Imagem Grid → Items*
 */
export interface ProjectDocumentDataBlocksBlocoImagemGridSliceItem {
	/**
	 * Imagem field in *Project → Slice zone → Bloco Imagem Grid → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.blocks[].bloco_imagem_grid.items.grid_image_url
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	grid_image_url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * Cor field in *Project → Slice zone → Bloco Imagem Grid → Items*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.blocks[].bloco_imagem_grid.items.grid_image_color
	 * - **Documentation**: https://prismic.io/docs/fields/color
	 */
	grid_image_color: prismic.ColorField;
	
	/**
	 * Nome field in *Project → Slice zone → Bloco Imagem Grid → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.blocks[].bloco_imagem_grid.items.grid_image_name
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	grid_image_name: prismic.KeyTextField;
}

/**
 * Slice for *Project → Slice zone*
 */
export type ProjectDocumentDataBlocksBlocoImagemGridSlice = prismic.Slice<"bloco_imagem_grid", Simplify<ProjectDocumentDataBlocksBlocoImagemGridSlicePrimary>, Simplify<ProjectDocumentDataBlocksBlocoImagemGridSliceItem>>

type ProjectDocumentDataBlocksSlice = ProjectDocumentDataBlocksBlocoFullImageSlice | ProjectDocumentDataBlocksBlocoImagemGridSlice

/**
 * Primary content in *Project → Slice zone → Page Config → Primary*
 */
export interface ProjectDocumentDataBodyPageConfigSlicePrimary {
	/**
	 * Background field in *Project → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.body[].page_config.primary.background_color
	 * - **Documentation**: https://prismic.io/docs/fields/color
	 */
	background_color: prismic.ColorField;
	
	/**
	 * SEO Title field in *Project → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.body[].page_config.primary.seo_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	seo_title: prismic.KeyTextField;
	
	/**
	 * SEO Description field in *Project → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.body[].page_config.primary.seo_description
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	seo_description: prismic.KeyTextField;
	
	/**
	 * SEO URL field in *Project → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.body[].page_config.primary.seo_url
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	seo_url: prismic.KeyTextField;
	
	/**
	 * Open Graph Type field in *Project → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: website
	 * - **API ID Path**: project.body[].page_config.primary.og_type
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	og_type: prismic.SelectField<"website" | "article" | "product" | "profile" | "video.movie", "filled">;
	
	/**
	 * Open Graph Title field in *Project → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.body[].page_config.primary.og_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	og_title: prismic.KeyTextField;
	
	/**
	 * Open Graph Description field in *Project → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.body[].page_config.primary.og_description
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	og_description: prismic.KeyTextField;
	
	/**
	 * Open Graph Image field in *Project → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.body[].page_config.primary.og_image
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	og_image: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * Twitter Card field in *Project → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: summary_large_image
	 * - **API ID Path**: project.body[].page_config.primary.twitter_card
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	twitter_card: prismic.SelectField<"summary_large_image" | "summary" | "player" | "app", "filled">;
	
	/**
	 * Twitter Title field in *Project → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.body[].page_config.primary.twitter_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	twitter_title: prismic.KeyTextField;
	
	/**
	 * Twitter Description field in *Project → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.body[].page_config.primary.twitter_description
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	twitter_description: prismic.KeyTextField;
	
	/**
	 * Twitter Image field in *Project → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.body[].page_config.primary.twitter_image
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	twitter_image: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Slice for *Project → Slice zone*
 */
export type ProjectDocumentDataBodyPageConfigSlice = prismic.Slice<"page_config", Simplify<ProjectDocumentDataBodyPageConfigSlicePrimary>, never>

type ProjectDocumentDataBodySlice = ProjectDocumentDataBodyPageConfigSlice

/**
 * Content for Project documents
 */
interface ProjectDocumentData {
	/**
	 * Nome field in *Project*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	name: prismic.KeyTextField;
	
	/**
	 * Descrição field in *Project*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	description: prismic.KeyTextField;
	
	/**
	 * Conteúdo field in *Project*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.content
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	content: prismic.RichTextField;
	
	/**
	 * Data field in *Project*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.date
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/date
	 */
	date: prismic.DateField;
	
	/**
	 * Destaque na Home field in *Project*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: project.highlight
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	highlight: prismic.BooleanField;
	
	/**
	 * tecnologias field in *Project*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.technologies[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	technologies: prismic.GroupField<Simplify<ProjectDocumentDataTechnologiesItem>>;/**
	 * Nome field in *Project*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.banner_name
	 * - **Tab**: Banner
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	banner_name: prismic.KeyTextField;
	
	/**
	 * Logo field in *Project*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.logo
	 * - **Tab**: Banner
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	logo: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * Cor do logo field in *Project*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.logo_color
	 * - **Tab**: Banner
	 * - **Documentation**: https://prismic.io/docs/fields/color
	 */
	logo_color: prismic.ColorField;
	
	/**
	 * Banner field in *Project*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.banner
	 * - **Tab**: Banner
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	banner: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * Banner classe field in *Project*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.banner_class
	 * - **Tab**: Banner
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	banner_class: prismic.KeyTextField;
	
	/**
	 * Thumbnail field in *Project*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.thumbnail
	 * - **Tab**: Banner
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	thumbnail: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * thumbnail classe field in *Project*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.thumbnail_class
	 * - **Tab**: Banner
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	thumbnail_class: prismic.KeyTextField;/**
	 * Slice zone field in *Project*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.blocks[]
	 * - **Tab**: Blocos
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	blocks: prismic.SliceZone<ProjectDocumentDataBlocksSlice>;/**
	 * De field in *Project*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.start_date
	 * - **Tab**: Detalhes
	 * - **Documentation**: https://prismic.io/docs/fields/date
	 */
	start_date: prismic.DateField;
	
	/**
	 * Até field in *Project*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.end_date
	 * - **Tab**: Detalhes
	 * - **Documentation**: https://prismic.io/docs/fields/date
	 */
	end_date: prismic.DateField;
	
	/**
	 * Equipe field in *Project*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.team_size
	 * - **Tab**: Detalhes
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	team_size: prismic.SelectField<"1" | "2 - 10" | "10 - 50" | "50 - 100" | "+ 100">;
	
	/**
	 * Cargo field in *Project*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.role
	 * - **Tab**: Detalhes
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	role: prismic.KeyTextField;
	
	/**
	 * Empresa field in *Project*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.company
	 * - **Tab**: Detalhes
	 * - **Documentation**: https://prismic.io/docs/fields/content-relationship
	 */
	company: prismic.ContentRelationshipField<"company">;/**
	 * Slice zone field in *Project*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.body[]
	 * - **Tab**: Config
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	body: prismic.SliceZone<ProjectDocumentDataBodySlice>;
}

/**
 * Project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<ProjectDocumentData>, "project", Lang>;

/**
 * Primary content in *Projects → Slice zone → Page Config → Primary*
 */
export interface ProjectsDocumentDataBodyPageConfigSlicePrimary {
	/**
	 * Background field in *Projects → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.body[].page_config.primary.background_color
	 * - **Documentation**: https://prismic.io/docs/fields/color
	 */
	background_color: prismic.ColorField;
	
	/**
	 * SEO Title field in *Projects → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.body[].page_config.primary.seo_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	seo_title: prismic.KeyTextField;
	
	/**
	 * SEO Description field in *Projects → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.body[].page_config.primary.seo_description
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	seo_description: prismic.KeyTextField;
	
	/**
	 * SEO URL field in *Projects → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.body[].page_config.primary.seo_url
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	seo_url: prismic.KeyTextField;
	
	/**
	 * Open Graph Type field in *Projects → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: website
	 * - **API ID Path**: projects.body[].page_config.primary.og_type
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	og_type: prismic.SelectField<"website" | "article" | "product" | "profile" | "video.movie", "filled">;
	
	/**
	 * Open Graph Title field in *Projects → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.body[].page_config.primary.og_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	og_title: prismic.KeyTextField;
	
	/**
	 * Open Graph Description field in *Projects → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.body[].page_config.primary.og_description
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	og_description: prismic.KeyTextField;
	
	/**
	 * Open Graph Image field in *Projects → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.body[].page_config.primary.og_image
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	og_image: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * Twitter Card field in *Projects → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: summary_large_image
	 * - **API ID Path**: projects.body[].page_config.primary.twitter_card
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	twitter_card: prismic.SelectField<"summary_large_image" | "summary" | "player" | "app", "filled">;
	
	/**
	 * Twitter Title field in *Projects → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.body[].page_config.primary.twitter_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	twitter_title: prismic.KeyTextField;
	
	/**
	 * Twitter Description field in *Projects → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.body[].page_config.primary.twitter_description
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	twitter_description: prismic.KeyTextField;
	
	/**
	 * Twitter Image field in *Projects → Slice zone → Page Config → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.body[].page_config.primary.twitter_image
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	twitter_image: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Slice for *Projects → Slice zone*
 */
export type ProjectsDocumentDataBodyPageConfigSlice = prismic.Slice<"page_config", Simplify<ProjectsDocumentDataBodyPageConfigSlicePrimary>, never>

type ProjectsDocumentDataBodySlice = ProjectsDocumentDataBodyPageConfigSlice

/**
 * Content for Projects documents
 */
interface ProjectsDocumentData {
	/**
	 * Título field in *Projects*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Alex Madeira
	 * - **API ID Path**: projects.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Sub título field in *Projects*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.sub_title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	sub_title: prismic.KeyTextField;
	
	/**
	 * Descrição field in *Projects*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;/**
	 * Slice zone field in *Projects*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.body[]
	 * - **Tab**: Config
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	body: prismic.SliceZone<ProjectsDocumentDataBodySlice>;
}

/**
 * Projects document from Prismic
 *
 * - **API ID**: `projects`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectsDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<ProjectsDocumentData>, "projects", Lang>;

/**
 * Content for Technology documents
 */
interface TechnologyDocumentData {
	/**
	 * Nome field in *Technology*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: technology.name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	name: prismic.KeyTextField;
	
	/**
	 * Escrever field in *Technology*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: technology.type
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	type: prismic.KeyTextField;
	
	/**
	 * Comecei em field in *Technology*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: *None*
	 * - **API ID Path**: technology.usage_started
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/date
	 */
	usage_started: prismic.DateField;
	
	/**
	 * Cor field in *Technology*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: technology.color
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/color
	 */
	color: prismic.ColorField;
	
	/**
	 * Banner field in *Technology*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: technology.banner
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	banner: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Technology document from Prismic
 *
 * - **API ID**: `technology`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TechnologyDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<TechnologyDocumentData>, "technology", Lang>;

export type AllDocumentTypes = AboutDocument | AwardDocument | BrandDocument | CompanyDocument | HomeDocument | ProjectDocument | ProjectsDocument | TechnologyDocument;

declare module "@prismicio/client" {
	interface CreateClient {
		(repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
	}
	
	interface CreateWriteClient {
		(repositoryNameOrEndpoint: string, options: prismic.WriteClientConfig): prismic.WriteClient<AllDocumentTypes>;
	}
	
	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}
	
	namespace Content {
		export type {
			AboutDocument,
			AboutDocumentData,
			AboutDocumentDataBodyPageConfigSlicePrimary,
			AboutDocumentDataBodySlice,
			AwardDocument,
			AwardDocumentData,
			BrandDocument,
			BrandDocumentData,
			CompanyDocument,
			CompanyDocumentData,
			HomeDocument,
			HomeDocumentData,
			HomeDocumentDataBodyPageConfigSlicePrimary,
			HomeDocumentDataBodySlice,
			ProjectDocument,
			ProjectDocumentData,
			ProjectDocumentDataTechnologiesItem,
			ProjectDocumentDataBlocksBlocoFullImageSlicePrimary,
			ProjectDocumentDataBlocksBlocoImagemGridSlicePrimary,
			ProjectDocumentDataBlocksBlocoImagemGridSliceItem,
			ProjectDocumentDataBlocksSlice,
			ProjectDocumentDataBodyPageConfigSlicePrimary,
			ProjectDocumentDataBodySlice,
			ProjectsDocument,
			ProjectsDocumentData,
			ProjectsDocumentDataBodyPageConfigSlicePrimary,
			ProjectsDocumentDataBodySlice,
			TechnologyDocument,
			TechnologyDocumentData,
			AllDocumentTypes
		}
	}
}