export const KEYBOARD_NUMBER_KEYS = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'] as const
export const KEYBOARD_SYMBOL_KEYS = ['`', '-', '=', '[', ']', '\\', ';', "'", ',', '.', '/'] as const
export const KEYBOARD_FUNCTION_KEYS = [
  'f1',
  'f2',
  'f3',
  'f4',
  'f5',
  'f6',
  'f7',
  'f8',
  'f9',
  'f10',
  'f11',
  'f12',
] as const
export const KEYBOARD_LETTER_KEYS = [
  'a',
  'b',
  'c',
  'd',
  'e',
  'f',
  'g',
  'h',
  'i',
  'j',
  'k',
  'l',
  'm',
  'n',
  'o',
  'p',
  'q',
  'r',
  's',
  't',
  'u',
  'v',
  'w',
  'x',
  'y',
  'z',
] as const
export const KEYBOARD_ARROW_KEYS = ['ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight'] as const
export const KEYBOARD_SPECIAL_KEYS = [
  'backspace',
  'tab',
  'enter',
  'return',
  'shift',
  'ctrl',
  'control',
  'alt',
  'option',
  'capslock',
  'esc',
  'escape',
  'space',
  'pageup',
  'pagedown',
  'end',
  'home',
  'left',
  'up',
  'right',
  'down',
  'ins',
  'insert',
  'del',
  'delete',
  'meta',
  'command',
  'cmd',
  'clear',
] as const
export const KEYBOARD_ALL_KEYS = [
  ...KEYBOARD_NUMBER_KEYS,
  ...KEYBOARD_FUNCTION_KEYS,
  ...KEYBOARD_ARROW_KEYS,
  ...KEYBOARD_SYMBOL_KEYS,
  ...KEYBOARD_LETTER_KEYS,
  ...KEYBOARD_SPECIAL_KEYS,
] as const
